spec:
  template:
    spec:
      containers:
        - resources:
              limits:
                memory: 500Mi
                cpu: 700m
              requests:
                memory: 500Mi
                cpu: 700m
